server:
  port: 8080
spring:
  application:
    name: admin-service
  profiles:
    active: docker
  thymeleaf:
    prefix:  classpath:/templates
    suffix: .html
    cache:  false
    mode: HTML
    encoding: UTF-8
eureka:
  client:
    service-url:
       defaultZone: http://eurekaservice:8761/eureka
  instance:
    prefer-ip-address: true