FROM java:8

RUN mkdir /app

WORKDIR /app

ADD business-service-impl.jar  /app/app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar","--spring.profiles.active=docker"]

EXPOSE 8020
